# Generated by Django 5.2.10 on 2026-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('template_code', models.SlugField(max_length=120)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('changelog', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('petition', 'Petition'), ('contract', 'Contract'), ('appeal', 'Appeal'), ('motion', 'Motion'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_code', '-created_at', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('template_code', 'version'), name='uniq_template_piece_code_version')],
            },
        ),
    ]
