# Generated by Django 5.2.10 on 2026-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepiece',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='templates_bank/uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='templatepiece',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='templatepiece',
            name='file_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
