# Generated by Django 5.2.10 on 2026-03-25 19:59

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_bank', '0002_templatepiece_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepiece',
            name='file_upload',
            field=models.FileField(blank=True, null=True, storage=config.storage.get_template_uploads_storage, upload_to='templates_bank/uploads/%Y/%m/%d'),
        ),
    ]
