# Generated by Django 5.2.12 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_bank', '0003_alter_templatepiece_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepiece',
            name='category',
            field=models.CharField(choices=[('petition', 'Petição'), ('contract', 'Contrato'), ('appeal', 'Recurso'), ('motion', 'Petição intermediária'), ('administrative', 'Administrativo'), ('other', 'Outro')], default='other', max_length=24),
        ),
        migrations.AlterField(
            model_name='templatepiece',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16),
        ),
    ]
