# Generated by Django 5.2.10 on 2026-02-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='decision',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('remove', 'Remove'), ('escalate', 'Escalate'), ('reject', 'Reject')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_moderated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='moderation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='open', max_length=16),
        ),
        migrations.CreateModel(
            name='ReportModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status_changed', 'Status changed'), ('approved', 'Approved'), ('removed', 'Removed'), ('escalated', 'Escalated'), ('rejected', 'Rejected'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned')], max_length=24)),
                ('from_status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='', max_length=16)),
                ('to_status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('rejected', 'Rejected')], default='', max_length=16)),
                ('from_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=16)),
                ('to_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('approve', 'Approve'), ('remove', 'Remove'), ('escalate', 'Escalate'), ('reject', 'Reject')], default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='community.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
