# Generated by Django 5.2.10 on 2026-02-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_moderated_at_comment_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('reports_per_warning', models.PositiveIntegerField(default=3)),
                ('max_warnings_before_ban', models.PositiveIntegerField(default=2)),
                ('auto_ban_on_threshold', models.BooleanField(default=False)),
                ('warning_message_template', models.TextField(default='Recebemos {removed_reports_total} denúncia(s) procedentes em conteúdos da sua conta. Este é o aviso {warning_number} de {max_warnings_before_ban}.')),
                ('ban_message_template', models.TextField(default='Sua conta foi suspensa por reincidência em violações da comunidade. Procure o suporte para revisão.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderation config',
                'verbose_name_plural': 'Moderation config',
            },
        ),
        migrations.CreateModel(
            name='UserModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning_issued', 'Warning issued'), ('ban_applied', 'Ban applied'), ('ban_revoked', 'Ban revoked')], max_length=24)),
                ('warning_number', models.PositiveIntegerField(blank=True, null=True)),
                ('removed_reports_total', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_moderation_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_moderation_events', to='community.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings_issued', models.PositiveIntegerField(default=0)),
                ('last_warning_at', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True, default='')),
                ('pending_login_message', models.TextField(blank=True, default='')),
                ('pending_login_message_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=16)),
                ('pending_login_message_created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_banned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
