# Generated by Django 5.2.10 on 2026-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_moderationconfig_usermoderationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationconfig',
            name='ban_scope',
            field=models.CharField(choices=[('community_only', 'Community only'), ('app_wide', 'App wide')], default='app_wide', max_length=24),
        ),
        migrations.AddField(
            model_name='usermoderationstatus',
            name='ban_scope',
            field=models.CharField(choices=[('community_only', 'Community only'), ('app_wide', 'App wide')], default='app_wide', max_length=24),
        ),
    ]
