# Generated by Django 5.2.10 on 2026-03-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_author_follows(apps, schema_editor):
    Post = apps.get_model('community', 'Post')
    PostFollow = apps.get_model('community', 'PostFollow')

    existing_pairs = set(
        PostFollow.objects.values_list('post_id', 'user_id')
    )
    to_create = []
    for post in Post.objects.all().only('id', 'author_id'):
        pair = (post.id, post.author_id)
        if pair in existing_pairs:
            continue
        to_create.append(
            PostFollow(
                post_id=post.id,
                user_id=post.author_id,
                is_active=True,
            )
        )

    if to_create:
        PostFollow.objects.bulk_create(to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_moderationconfig_ban_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='community_post_follow_unique')],
            },
        ),
        migrations.RunPython(seed_author_follows, migrations.RunPython.noop),
    ]
