# Generated by Django 5.2.10 on 2026-03-25 16:28

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


def backfill_community_public_metrics(apps, schema_editor):
    Post = apps.get_model('community', 'Post')
    Comment = apps.get_model('community', 'Comment')
    PostLike = apps.get_model('community', 'PostLike')
    CommentLike = apps.get_model('community', 'CommentLike')

    active_comment_state = 'active'

    for post in Post.objects.all().iterator():
        active_comments = Comment.objects.filter(post_id=post.id, moderation_state=active_comment_state)
        comments_count = active_comments.count()
        last_comment_at = active_comments.aggregate(last_comment_at=Max('created_at'))['last_comment_at']
        likes_count = PostLike.objects.filter(post_id=post.id, is_active=True).count()

        post.comments_count = comments_count
        post.last_comment_at = last_comment_at
        post.last_activity_at = last_comment_at or post.created_at
        post.likes_count = likes_count
        post.save(update_fields=['comments_count', 'last_comment_at', 'last_activity_at', 'likes_count', 'updated_at'])

    like_counts = (
        CommentLike.objects.filter(is_active=True)
        .values('comment_id')
        .annotate(likes_count=Count('id'))
    )
    counts_by_comment_id = {row['comment_id']: row['likes_count'] for row in like_counts}
    for comment in Comment.objects.all().iterator():
        comment.likes_count = counts_by_comment_id.get(comment.id, 0)
        comment.save(update_fields=['likes_count', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_postlike_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_activity_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'moderation_state', 'created_at'], name='comm_comment_post_state_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', 'is_active'], name='comm_comment_like_state_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['moderation_state', 'last_activity_at', 'created_at'], name='comm_post_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'moderation_state', 'last_activity_at', 'created_at'], name='comm_post_cat_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'is_active'], name='comm_post_like_state_idx'),
        ),
        migrations.RunPython(backfill_community_public_metrics, migrations.RunPython.noop),
    ]
