# Generated by Django 5.2.12 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_post_options_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation_state',
            field=models.CharField(choices=[('active', 'Ativo'), ('under_review', 'Em análise'), ('removed', 'Removido')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='moderationconfig',
            name='ban_scope',
            field=models.CharField(choices=[('community_only', 'Apenas comunidade'), ('app_wide', 'Aplicativo inteiro')], default='app_wide', max_length=24),
        ),
        migrations.AlterField(
            model_name='post',
            name='moderation_state',
            field=models.CharField(choices=[('active', 'Ativo'), ('under_review', 'Em análise'), ('removed', 'Removido')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='decision',
            field=models.CharField(blank=True, choices=[('approve', 'Aprovar'), ('remove', 'Remover'), ('escalate', 'Escalar'), ('reject', 'Rejeitar')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_review', 'Em análise'), ('resolved', 'Resolvida'), ('escalated', 'Escalada'), ('rejected', 'Rejeitada')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='reportmoderationaction',
            name='action_type',
            field=models.CharField(choices=[('status_changed', 'Status alterado'), ('approved', 'Aprovada'), ('removed', 'Removida'), ('escalated', 'Escalada'), ('rejected', 'Rejeitada'), ('priority_changed', 'Prioridade alterada'), ('assigned', 'Atribuída')], max_length=24),
        ),
        migrations.AlterField(
            model_name='usermoderationevent',
            name='action_type',
            field=models.CharField(choices=[('warning_issued', 'Aviso emitido'), ('ban_applied', 'Banimento aplicado'), ('ban_revoked', 'Banimento revogado')], max_length=24),
        ),
        migrations.AlterField(
            model_name='usermoderationstatus',
            name='ban_scope',
            field=models.CharField(choices=[('community_only', 'Apenas comunidade'), ('app_wide', 'Aplicativo inteiro')], default='app_wide', max_length=24),
        ),
        migrations.AlterField(
            model_name='usermoderationstatus',
            name='pending_login_message_level',
            field=models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('danger', 'Crítico')], default='info', max_length=16),
        ),
    ]
