# Generated by Django 5.2.10 on 2026-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notificationevent_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', 'Membro'), ('moderator', 'Moderador'), ('owner', 'Dono')], default='member', max_length=16),
        ),
    ]
