# Generated by Django 5.2.10 on 2026-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='community_interaction_updates_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('book_version_published', 'Book version published'), ('content_published', 'Content published'), ('course_content_published', 'Course content published'), ('caselaw_published', 'Caselaw published'), ('community_interaction', 'Community interaction')], max_length=48),
        ),
    ]
