# Generated by Django 5.2.10 on 2026-03-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notificationdispatch_acknowledged_at_pushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdispatch',
            name='channel',
            field=models.CharField(choices=[('push', 'Push'), ('in_app', 'In-app')], default='push', max_length=16),
        ),
    ]
