# Generated by Django 5.2.10 on 2026-03-25 19:59

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=config.storage.get_avatar_storage, upload_to='avatars/'),
        ),
    ]
