# Generated by Django 5.2.12 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprivacyrequest',
            name='request_type',
            field=models.CharField(choices=[('export', 'Exportação'), ('erasure', 'Eliminação')], max_length=16),
        ),
        migrations.AlterField(
            model_name='dataprivacyrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitada'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdispatch',
            name='channel',
            field=models.CharField(choices=[('push', 'Push'), ('in_app', 'No app')], default='push', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('skipped', 'Ignorado'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(choices=[('book_version_published', 'Nova versão de livro publicada'), ('content_published', 'Novo conteúdo publicado'), ('course_content_published', 'Novo conteúdo do curso publicado'), ('caselaw_published', 'Nova jurisprudência publicada'), ('community_interaction', 'Interação na comunidade')], max_length=48),
        ),
    ]
