# Generated by Django 5.2.12 on 2026-04-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_pushdevice_installation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_of_use', 'Termos de uso'), ('privacy_policy', 'Política de privacidade')], max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('content_html', models.TextField()),
                ('content_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('enforcement_starts_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', '-published_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'version'), name='uniq_legal_document_type_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type',), name='uniq_active_legal_document_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn')], max_length=32)),
                ('provider_subject', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('provider_claims', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='uniq_external_identity_provider_subject'), models.UniqueConstraint(fields=('user', 'provider'), name='uniq_external_identity_per_user_provider')],
            },
        ),
        migrations.CreateModel(
            name='UserLegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('login_gate', 'Barreira de aceite'), ('account_settings', 'Minha conta'), ('admin', 'Admin')], default='login_gate', max_length=32)),
                ('app_platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('system', 'Sistema')], default='web', max_length=16)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='accounts.legaldocumentversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='uniq_user_legal_acceptance_per_document')],
            },
        ),
    ]
