# Generated by Django 5.2.10 on 2026-02-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
        ('library', '0003_pagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='library.book'),
        ),
    ]
