# Generated by Django 5.2.10 on 2026-02-12 15:16

from django.db import migrations


def normalize_legacy_entitlement_scope(apps, schema_editor):
    Entitlement = apps.get_model('entitlements', 'Entitlement')

    # Registros antigos de product='book' não tinham book_id.
    # Para manter o mesmo efeito de acesso global, converte para subscription.
    Entitlement.objects.filter(product='book', book__isnull=True).update(product='subscription')

    # Garante coerência para subscription antes do constraint.
    Entitlement.objects.filter(product='subscription').update(book=None)


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0002_entitlement_book_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_entitlement_scope, migrations.RunPython.noop),
    ]
