# Generated by Django 5.2.10 on 2026-02-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0003_entitlement_scope_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('book__isnull', True), ('product', 'subscription')),
                    models.Q(('book__isnull', False), ('product', 'book')),
                    _connector='OR',
                ),
                name='entitlement_scope_matches_product',
            ),
        ),
    ]
