# Generated by Django 5.2.10 on 2026-02-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0004_entitlement_scope_constraint'),
        ('library', '0003_pagetext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('essential', 'Essencial'), ('professional', 'Profissional')], default='essential', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa'), ('canceled', 'Cancelada')], default='inactive', max_length=16)),
                ('is_founder', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='entitlement',
            name='entitlement_scope_matches_product',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='entitlements.subscription'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('book__isnull', True), ('product', 'subscription')), models.Q(('book__isnull', False), ('product', 'book'), ('subscription__isnull', True)), _connector='OR'), name='entitlement_scope_matches_product'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_subscription_per_user'),
        ),
    ]
