# Generated by Django 5.2.10 on 2026-02-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=150)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content_rich', models.TextField(blank=True, default='')),
                ('content_plain', models.TextField(blank=True, default='', editable=False)),
                ('post_type', models.CharField(choices=[('blog', 'Blog'), ('lesson', 'Lesson'), ('announcement', 'Announcement')], default='blog', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('asset_type', models.CharField(choices=[('pdf', 'PDF'), ('checklist', 'Checklist'), ('model', 'Model'), ('video', 'Video'), ('link', 'Link'), ('other', 'Other')], default='pdf', max_length=24)),
                ('file_url', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='courses.coursepost')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('live_class', 'Live class'), ('mentoring', 'Mentoring'), ('webinar', 'Webinar')], default='live_class', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_events', to='courses.coursepost')),
            ],
            options={
                'ordering': ['-starts_at', '-updated_at', '-created_at'],
            },
        ),
    ]
