# Generated by Django 5.2.12 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseasset',
            name='asset_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('checklist', 'Checklist'), ('model', 'Modelo'), ('video', 'Vídeo'), ('link', 'Link'), ('other', 'Outro')], default='pdf', max_length=24),
        ),
        migrations.AlterField(
            model_name='courseasset',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='coursepost',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Artigo'), ('lesson', 'Aula'), ('announcement', 'Aviso')], default='blog', max_length=24),
        ),
        migrations.AlterField(
            model_name='coursepost',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='event_type',
            field=models.CharField(choices=[('live_class', 'Aula ao vivo'), ('mentoring', 'Mentoria'), ('webinar', 'Webinário')], default='live_class', max_length=24),
        ),
        migrations.AlterField(
            model_name='liveevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('live', 'Ao vivo'), ('finished', 'Encerrada'), ('canceled', 'Cancelada')], default='draft', max_length=16),
        ),
    ]
