"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url
import os
import sys

from .logging import build_logging_config


def env_bool(key: str, default: bool = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_list(key: str, default: str = "") -> list[str]:
    raw = os.getenv(key)
    value = raw if raw is not None else default
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


# Load dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = os.getenv("DJANGO_ENV", "development").strip().lower()
IS_PRODUCTION = DJANGO_ENV in {"prod", "production"}
IS_STAGE = DJANGO_ENV in {"stage", "staging"}
IS_TESTING = "test" in sys.argv
APP_VERSION = (os.getenv("APP_VERSION") or "dev").strip()

# SECURITY WARNING: don't run with debug turned on in production/stage!
DEBUG = env_bool("DEBUG", default=not (IS_PRODUCTION or IS_STAGE))

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG must be false when DJANGO_ENV=production.")

secret_key = os.getenv("DJANGO_SECRET_KEY")
if secret_key:
    SECRET_KEY = secret_key
elif IS_PRODUCTION or IS_STAGE:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is required when DJANGO_ENV is stage/production."
    )
else:
    # Dev-only fallback.
    SECRET_KEY = "dev-insecure-secret-key"

allowed_hosts_default = "localhost,127.0.0.1" if DEBUG else ""
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", allowed_hosts_default)

if (IS_PRODUCTION or IS_STAGE) and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS is required when DJANGO_ENV is stage/production."
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'tinymce',

    'accounts',
    'annotations',
    'caselaw',
    'community',
    'courses',
    'entitlements',
    'library',
    'search',
    'templates_bank',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = os.getenv("DATABASE_URL")
if (IS_PRODUCTION or IS_STAGE) and not database_url:
    raise ImproperlyConfigured(
        "DATABASE_URL is required when DJANGO_ENV is stage/production."
    )

DATABASES = {
    'default': dj_database_url.config(
        default=database_url or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=60,
        conn_health_checks=True,
    )
}

cache_timeout_seconds = int(os.getenv('DJANGO_CACHE_TIMEOUT_SECONDS', '300'))
redis_url = (os.getenv('REDIS_URL') or '').strip()

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': redis_url,
        'TIMEOUT': cache_timeout_seconds,
    }
    if redis_url
    else {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'livro-vivo-api-default-cache',
        'TIMEOUT': cache_timeout_seconds,
    }
}

if IS_TESTING:
    # Testes determinísticos e independentes de serviços externos.
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        'TEST': {'NAME': ':memory:'},
    }
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'livro-vivo-api-test-cache',
            'TIMEOUT': cache_timeout_seconds,
        }
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_register': '5/min',
        'auth_login': '10/min',
        'library_search': '60/min',
        'global_search': '60/min',
        'community_api': '120/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEMPLATES_BANK_DOWNLOAD_TOKEN_MAX_AGE_SECONDS = int(
    os.getenv('TEMPLATES_BANK_DOWNLOAD_TOKEN_MAX_AGE_SECONDS', '300')
)
TEMPLATES_BANK_REMOTE_FILE_FETCH_TIMEOUT_SECONDS = int(
    os.getenv('TEMPLATES_BANK_REMOTE_FILE_FETCH_TIMEOUT_SECONDS', '8')
)
TEMPLATES_BANK_REMOTE_FILE_MAX_BYTES = int(
    os.getenv('TEMPLATES_BANK_REMOTE_FILE_MAX_BYTES', str(30 * 1024 * 1024))
)

NOTIFICATIONS_ENABLED = env_bool('NOTIFICATIONS_ENABLED', default=True)
NOTIFICATIONS_PUSH_PROVIDER = (os.getenv('NOTIFICATIONS_PUSH_PROVIDER') or 'noop').strip().lower()
NOTIFICATIONS_FCM_PROJECT_ID = (os.getenv('NOTIFICATIONS_FCM_PROJECT_ID') or '').strip()
NOTIFICATIONS_APNS_TOPIC = (os.getenv('NOTIFICATIONS_APNS_TOPIC') or '').strip()

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_default_dev_cors = (
    'http://localhost:8081,'
    'http://127.0.0.1:8081,'
    'http://localhost:8082,'
    'http://127.0.0.1:8082,'
    'http://localhost:19006,'
    'http://127.0.0.1:19006'
)

_default_non_production_cors = _default_dev_cors if not (IS_PRODUCTION or IS_STAGE) else ''

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    _default_non_production_cors,
)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = env_bool('DJANGO_CORS_ALLOW_CREDENTIALS', default=False)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', '')

if (IS_PRODUCTION or IS_STAGE) and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CORS_ALLOWED_ORIGINS is required when DJANGO_ENV is stage/production."
    )
if (IS_PRODUCTION or IS_STAGE) and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CSRF_TRUSTED_ORIGINS is required when DJANGO_ENV is stage/production."
    )

SECURE_SSL_REDIRECT = env_bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    default=(IS_PRODUCTION or IS_STAGE),
)
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env_bool(
    'DJANGO_SESSION_COOKIE_SECURE',
    default=(IS_PRODUCTION or IS_STAGE),
)
CSRF_COOKIE_SECURE = env_bool(
    'DJANGO_CSRF_COOKIE_SECURE',
    default=(IS_PRODUCTION or IS_STAGE),
)
SECURE_HSTS_SECONDS = int(
    os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000' if IS_PRODUCTION else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = env_bool(
    'DJANGO_SECURE_HSTS_PRELOAD',
    default=IS_PRODUCTION,
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'

if env_bool('DJANGO_SECURE_PROXY_SSL_HEADER_ENABLED', default=(IS_PRODUCTION or IS_STAGE)):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SENTRY_DSN = (os.getenv("SENTRY_DSN") or "").strip()
SENTRY_ENVIRONMENT = (os.getenv("SENTRY_ENVIRONMENT") or DJANGO_ENV).strip()
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0"))

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=SENTRY_ENVIRONMENT,
            release=APP_VERSION,
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,
            integrations=[DjangoIntegration()],
        )
    except Exception:
        # Não impede boot em caso de configuração parcial de observabilidade.
        pass

DJANGO_LOG_PROFILE = (os.getenv('DJANGO_LOG_PROFILE') or ('dev' if DEBUG else 'prod')).strip().lower()
DJANGO_LOG_LEVEL = (os.getenv('DJANGO_LOG_LEVEL') or '').strip().upper() or None
DJANGO_LOG_DJANGO_LEVEL = (os.getenv('DJANGO_LOG_DJANGO_LEVEL') or '').strip().upper() or None
DJANGO_LOG_INCLUDE_REQUESTS = env_bool('DJANGO_LOG_INCLUDE_REQUESTS', default=DEBUG)
DJANGO_LOG_STRUCTURED = env_bool(
    'DJANGO_LOG_STRUCTURED',
    default=DJANGO_LOG_PROFILE in {'prod', 'production', 'stage', 'staging'},
)

LOGGING = build_logging_config(
    debug=DEBUG,
    profile=DJANGO_LOG_PROFILE,
    root_level=DJANGO_LOG_LEVEL,
    django_level=DJANGO_LOG_DJANGO_LEVEL,
    include_request_logs=DJANGO_LOG_INCLUDE_REQUESTS,
    structured=DJANGO_LOG_STRUCTURED,
)
