"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url
import os
import sys

from .logging import build_logging_config
from .runtime import is_check_only_migration_command
from .storage import (
    DEFAULT_MEDIA_PRIVATE_CACHE_CONTROL,
    DEFAULT_MEDIA_PUBLIC_CACHE_CONTROL,
    build_storage_policies,
    build_storage_settings,
    normalize_media_url,
    resolve_media_root,
)


def env_bool(key: str, default: bool = False) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def env_list(key: str, default: str = "") -> list[str]:
    raw = os.getenv(key)
    value = raw if raw is not None else default
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


# Load dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = os.getenv("DJANGO_ENV", "development").strip().lower()
IS_PRODUCTION = DJANGO_ENV in {"prod", "production"}
IS_STAGE = DJANGO_ENV in {"stage", "staging"}
IS_TESTING = "test" in sys.argv
OFFLINE_MIGRATION_CHECK = (
    not (IS_PRODUCTION or IS_STAGE)
    and env_bool("DJANGO_OFFLINE_MIGRATION_CHECK", default=True)
    and is_check_only_migration_command()
)
APP_VERSION = (os.getenv("APP_VERSION") or "dev").strip()

# SECURITY WARNING: don't run with debug turned on in production/stage!
DEBUG = env_bool("DEBUG", default=not (IS_PRODUCTION or IS_STAGE))

if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG must be false when DJANGO_ENV=production.")

secret_key = os.getenv("DJANGO_SECRET_KEY")
if secret_key:
    SECRET_KEY = secret_key
elif IS_PRODUCTION or IS_STAGE:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is required when DJANGO_ENV is stage/production."
    )
else:
    # Dev-only fallback.
    SECRET_KEY = "dev-insecure-secret-key"

allowed_hosts_default = "localhost,127.0.0.1" if DEBUG else ""
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", allowed_hosts_default)

if (IS_PRODUCTION or IS_STAGE) and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS is required when DJANGO_ENV is stage/production."
    )

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'tinymce',

    'accounts',
    'annotations',
    'caselaw',
    'community',
    'courses',
    'entitlements',
    'library',
    'search',
    'templates_bank',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.RequestContextMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.admin_context.admin_current_path',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = None if OFFLINE_MIGRATION_CHECK else os.getenv("DATABASE_URL")
if (IS_PRODUCTION or IS_STAGE) and not database_url:
    raise ImproperlyConfigured(
        "DATABASE_URL is required when DJANGO_ENV is stage/production."
    )

if OFFLINE_MIGRATION_CHECK:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=60,
            conn_health_checks=True,
        )
    }

cache_timeout_seconds = int(os.getenv('DJANGO_CACHE_TIMEOUT_SECONDS', '300'))
redis_url = (os.getenv('REDIS_URL') or '').strip()

if (IS_PRODUCTION or IS_STAGE) and not IS_TESTING and not redis_url:
    raise ImproperlyConfigured(
        "REDIS_URL is required when DJANGO_ENV is stage/production."
    )

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': redis_url,
        'TIMEOUT': cache_timeout_seconds,
    }
    if redis_url
    else {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'livro-vivo-api-default-cache',
        'TIMEOUT': cache_timeout_seconds,
    }
}

if IS_TESTING:
    # Testes determinísticos e independentes de serviços externos.
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        'TEST': {'NAME': ':memory:'},
    }
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'livro-vivo-api-test-cache',
            'TIMEOUT': cache_timeout_seconds,
        }
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_register': '5/min',
        'auth_login': '10/min',
        'auth_password_reset': '5/min',
        'auth_password_reset_confirm': '10/min',
        'auth_refresh': '30/min',
        'library_search': '60/min',
        'global_search': '45/min',
        'courses_api': '90/min',
        'templates_bank_api': '90/min',
        'notifications_sensitive': '60/min',
        'community_api': '120/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEMPLATES_BANK_DOWNLOAD_TOKEN_MAX_AGE_SECONDS = int(
    os.getenv('TEMPLATES_BANK_DOWNLOAD_TOKEN_MAX_AGE_SECONDS', '60')
)

_default_email_backend = (
    'django.core.mail.backends.locmem.EmailBackend'
    if IS_TESTING
    else 'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', _default_email_backend)
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env_bool('DJANGO_EMAIL_USE_SSL', default=False)
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'Livro Vivo <no-reply@livrovivo.local>')
TEMPLATES_BANK_REMOTE_FILE_FETCH_TIMEOUT_SECONDS = int(
    os.getenv('TEMPLATES_BANK_REMOTE_FILE_FETCH_TIMEOUT_SECONDS', '8')
)
TEMPLATES_BANK_REMOTE_FILE_MAX_BYTES = int(
    os.getenv('TEMPLATES_BANK_REMOTE_FILE_MAX_BYTES', str(30 * 1024 * 1024))
)
SOCIAL_AUTH_ALLOWED_REDIRECT_URIS = env_list(
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS',
    'http://localhost:8081/auth/callback,http://127.0.0.1:8081/auth/callback,livrovivo://auth/callback',
)
SOCIAL_AUTH_STATE_MAX_AGE_SECONDS = int(
    os.getenv('SOCIAL_AUTH_STATE_MAX_AGE_SECONDS', '600')
)
SOCIAL_AUTH_RESULT_TOKEN_MAX_AGE_SECONDS = int(
    os.getenv('SOCIAL_AUTH_RESULT_TOKEN_MAX_AGE_SECONDS', '300')
)
SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS = int(
    os.getenv('SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS', '8')
)
SOCIAL_AUTH_GOOGLE_ENABLED = env_bool('SOCIAL_AUTH_GOOGLE_ENABLED', default=False)
SOCIAL_AUTH_GOOGLE_CLIENT_ID = (os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_ID') or '').strip()
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = (os.getenv('SOCIAL_AUTH_GOOGLE_CLIENT_SECRET') or '').strip()
SOCIAL_AUTH_GOOGLE_AUTHORIZATION_URL = (
    os.getenv('SOCIAL_AUTH_GOOGLE_AUTHORIZATION_URL')
    or 'https://accounts.google.com/o/oauth2/v2/auth'
).strip()
SOCIAL_AUTH_GOOGLE_TOKEN_URL = (
    os.getenv('SOCIAL_AUTH_GOOGLE_TOKEN_URL')
    or 'https://oauth2.googleapis.com/token'
).strip()
SOCIAL_AUTH_GOOGLE_USERINFO_URL = (
    os.getenv('SOCIAL_AUTH_GOOGLE_USERINFO_URL')
    or 'https://openidconnect.googleapis.com/v1/userinfo'
).strip()
SOCIAL_AUTH_GOOGLE_SCOPES = tuple(
    item.strip()
    for item in env_list(
        'SOCIAL_AUTH_GOOGLE_SCOPES',
        'openid,email,profile',
    )
    if item.strip()
)
SOCIAL_AUTH_LINKEDIN_ENABLED = env_bool('SOCIAL_AUTH_LINKEDIN_ENABLED', default=False)
SOCIAL_AUTH_LINKEDIN_CLIENT_ID = (os.getenv('SOCIAL_AUTH_LINKEDIN_CLIENT_ID') or '').strip()
SOCIAL_AUTH_LINKEDIN_CLIENT_SECRET = (os.getenv('SOCIAL_AUTH_LINKEDIN_CLIENT_SECRET') or '').strip()
SOCIAL_AUTH_LINKEDIN_AUTHORIZATION_URL = (
    os.getenv('SOCIAL_AUTH_LINKEDIN_AUTHORIZATION_URL')
    or 'https://www.linkedin.com/oauth/v2/authorization'
).strip()
SOCIAL_AUTH_LINKEDIN_TOKEN_URL = (
    os.getenv('SOCIAL_AUTH_LINKEDIN_TOKEN_URL')
    or 'https://www.linkedin.com/oauth/v2/accessToken'
).strip()
SOCIAL_AUTH_LINKEDIN_USERINFO_URL = (
    os.getenv('SOCIAL_AUTH_LINKEDIN_USERINFO_URL')
    or 'https://api.linkedin.com/v2/userinfo'
).strip()
SOCIAL_AUTH_LINKEDIN_SCOPES = tuple(
    item.strip()
    for item in env_list(
        'SOCIAL_AUTH_LINKEDIN_SCOPES',
        'openid,profile,email',
    )
    if item.strip()
)

METRICS_ENABLED = env_bool('DJANGO_METRICS_ENABLED', default=False)
METRICS_BEARER_TOKEN = (os.getenv('DJANGO_METRICS_BEARER_TOKEN') or '').strip()
if (IS_PRODUCTION or IS_STAGE) and METRICS_ENABLED and not METRICS_BEARER_TOKEN:
    raise ImproperlyConfigured(
        'DJANGO_METRICS_BEARER_TOKEN is required when metrics are enabled in stage/production.'
    )

NOTIFICATIONS_ENABLED = env_bool('NOTIFICATIONS_ENABLED', default=True)
NOTIFICATIONS_PUSH_PROVIDER = (os.getenv('NOTIFICATIONS_PUSH_PROVIDER') or 'noop').strip().lower()
NOTIFICATIONS_FCM_PROJECT_ID = (os.getenv('NOTIFICATIONS_FCM_PROJECT_ID') or '').strip()
NOTIFICATIONS_APNS_TOPIC = (os.getenv('NOTIFICATIONS_APNS_TOPIC') or '').strip()
PUSH_AUTODISPATCH_ENABLED = env_bool('PUSH_AUTODISPATCH_ENABLED', default=True)
EXPO_PUSH_API_URL = (
    os.getenv('EXPO_PUSH_API_URL') or 'https://exp.host/--/api/v2/push/send'
).strip()
EXPO_PUSH_ACCESS_TOKEN = (os.getenv('EXPO_PUSH_ACCESS_TOKEN') or '').strip()

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_BACKEND = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if (IS_PRODUCTION or IS_STAGE)
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)
MEDIA_STORAGE_PROVIDER = (os.getenv('DJANGO_STORAGE_PROVIDER') or 'filesystem').strip().lower()
MEDIA_URL = normalize_media_url(os.getenv('DJANGO_MEDIA_URL', '/media/'))
MEDIA_ROOT = resolve_media_root(base_dir=BASE_DIR, raw_value=os.getenv('DJANGO_MEDIA_ROOT'))
MEDIA_PUBLIC_CACHE_CONTROL = (
    os.getenv('DJANGO_MEDIA_PUBLIC_CACHE_CONTROL') or DEFAULT_MEDIA_PUBLIC_CACHE_CONTROL
).strip()
MEDIA_PRIVATE_CACHE_CONTROL = (
    os.getenv('DJANGO_MEDIA_PRIVATE_CACHE_CONTROL') or DEFAULT_MEDIA_PRIVATE_CACHE_CONTROL
).strip()
STORAGES = build_storage_settings(
    provider=MEDIA_STORAGE_PROVIDER,
    staticfiles_backend=STATICFILES_BACKEND,
    media_public_cache_control=MEDIA_PUBLIC_CACHE_CONTROL,
    media_private_cache_control=MEDIA_PRIVATE_CACHE_CONTROL,
    s3_bucket_name=(os.getenv('DJANGO_STORAGE_S3_BUCKET_NAME') or '').strip(),
    s3_endpoint_url=(os.getenv('DJANGO_STORAGE_S3_ENDPOINT_URL') or '').strip(),
    s3_region_name=(os.getenv('DJANGO_STORAGE_S3_REGION_NAME') or '').strip(),
    s3_access_key_id=(os.getenv('DJANGO_STORAGE_S3_ACCESS_KEY_ID') or '').strip(),
    s3_secret_access_key=(os.getenv('DJANGO_STORAGE_S3_SECRET_ACCESS_KEY') or '').strip(),
    s3_custom_domain=(os.getenv('DJANGO_STORAGE_S3_CUSTOM_DOMAIN') or '').strip(),
    s3_querystring_expire=int(os.getenv('DJANGO_STORAGE_S3_QUERYSTRING_EXPIRE', '300')),
)
MEDIA_STORAGE_POLICIES = build_storage_policies(
    provider=MEDIA_STORAGE_PROVIDER,
    media_public_cache_control=MEDIA_PUBLIC_CACHE_CONTROL,
    media_private_cache_control=MEDIA_PRIVATE_CACHE_CONTROL,
)
AVATAR_MAX_UPLOAD_BYTES = int(os.getenv('DJANGO_AVATAR_MAX_UPLOAD_BYTES', str(5 * 1024 * 1024)))
AVATAR_MAX_DIMENSION = int(os.getenv('DJANGO_AVATAR_MAX_DIMENSION', '1024'))
AVATAR_ALLOWED_MIME_TYPES = tuple(
    item.strip()
    for item in env_list(
        'DJANGO_AVATAR_ALLOWED_MIME_TYPES',
        'image/jpeg,image/png,image/webp',
    )
    if item.strip()
)
WHITENOISE_MAX_AGE = 31536000 if (IS_PRODUCTION or IS_STAGE) else 0
# TinyMCE resolves skins/plugins/themes via relative URLs at runtime.
# Keep the unhashed originals alongside the hashed assets in stage/prod.
WHITENOISE_KEEP_ONLY_HASHED_FILES = False
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_default_dev_cors = (
    'http://localhost:8081,'
    'http://127.0.0.1:8081,'
    'http://localhost:8082,'
    'http://127.0.0.1:8082,'
    'http://localhost:19006,'
    'http://127.0.0.1:19006'
)

_default_non_production_cors = _default_dev_cors if not (IS_PRODUCTION or IS_STAGE) else ''

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    _default_non_production_cors,
)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = env_bool('DJANGO_CORS_ALLOW_CREDENTIALS', default=False)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', '')

if (IS_PRODUCTION or IS_STAGE) and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CORS_ALLOWED_ORIGINS is required when DJANGO_ENV is stage/production."
    )
if (IS_PRODUCTION or IS_STAGE) and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CSRF_TRUSTED_ORIGINS is required when DJANGO_ENV is stage/production."
    )

APP_PUBLIC_BASE_URL = (os.getenv('APP_PUBLIC_BASE_URL') or (CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else '')).rstrip('/')
PASSWORD_RESET_CONFIRM_URL = (
    os.getenv('PASSWORD_RESET_CONFIRM_URL')
    or (f'{APP_PUBLIC_BASE_URL}/?password_reset=1' if APP_PUBLIC_BASE_URL else 'http://127.0.0.1:8081/?password_reset=1')
)
PASSWORD_RESET_CONFIRM_URL = PASSWORD_RESET_CONFIRM_URL.strip()

SECURE_SSL_REDIRECT = env_bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    default=(IS_PRODUCTION or IS_STAGE),
)
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env_bool(
    'DJANGO_SESSION_COOKIE_SECURE',
    default=(IS_PRODUCTION or IS_STAGE),
)
CSRF_COOKIE_SECURE = env_bool(
    'DJANGO_CSRF_COOKIE_SECURE',
    default=(IS_PRODUCTION or IS_STAGE),
)
SECURE_HSTS_SECONDS = int(
    os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000' if IS_PRODUCTION else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=IS_PRODUCTION,
)
SECURE_HSTS_PRELOAD = env_bool(
    'DJANGO_SECURE_HSTS_PRELOAD',
    default=IS_PRODUCTION,
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'

if env_bool('DJANGO_SECURE_PROXY_SSL_HEADER_ENABLED', default=(IS_PRODUCTION or IS_STAGE)):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SENTRY_DSN = (os.getenv("SENTRY_DSN") or "").strip()
SENTRY_ENVIRONMENT = (os.getenv("SENTRY_ENVIRONMENT") or DJANGO_ENV).strip()
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0"))

if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=SENTRY_ENVIRONMENT,
            release=APP_VERSION,
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,
            integrations=[DjangoIntegration()],
        )
    except Exception:
        # Não impede boot em caso de configuração parcial de observabilidade.
        pass

DJANGO_LOG_PROFILE = (os.getenv('DJANGO_LOG_PROFILE') or ('dev' if DEBUG else 'prod')).strip().lower()
DJANGO_LOG_LEVEL = (os.getenv('DJANGO_LOG_LEVEL') or '').strip().upper() or None
DJANGO_LOG_DJANGO_LEVEL = (os.getenv('DJANGO_LOG_DJANGO_LEVEL') or '').strip().upper() or None
DJANGO_LOG_INCLUDE_REQUESTS = env_bool('DJANGO_LOG_INCLUDE_REQUESTS', default=DEBUG)
DJANGO_LOG_STRUCTURED = env_bool(
    'DJANGO_LOG_STRUCTURED',
    default=DJANGO_LOG_PROFILE in {'prod', 'production', 'stage', 'staging'},
)

LOGGING = build_logging_config(
    debug=DEBUG,
    profile=DJANGO_LOG_PROFILE,
    root_level=DJANGO_LOG_LEVEL,
    django_level=DJANGO_LOG_DJANGO_LEVEL,
    include_request_logs=DJANGO_LOG_INCLUDE_REQUESTS,
    structured=DJANGO_LOG_STRUCTURED,
)
