# Generated by Django 5.2.10 on 2026-02-24 14:37

import django.db.models.deletion
from django.db import migrations, models


def _resolve_chapter_for_annotation(annotation, BookChapter, max_order_fn):
    version_id = annotation.book_version_id
    legacy_page = getattr(annotation, 'page_number', None)

    if legacy_page is not None:
        chapter = (
            BookChapter.objects
            .filter(book_version_id=version_id, order=legacy_page)
            .order_by('id')
            .first()
        )
        if chapter:
            return chapter

    chapter = (
        BookChapter.objects
        .filter(book_version_id=version_id)
        .order_by('order', 'id')
        .first()
    )
    if chapter:
        return chapter

    next_order = max_order_fn(version_id) + 1
    slug_base = 'legacy-annotations'
    slug = slug_base
    suffix = 2
    while BookChapter.objects.filter(book_version_id=version_id, slug=slug).exists():
        slug = f'{slug_base}-{suffix}'
        suffix += 1

    return BookChapter.objects.create(
        book_version_id=version_id,
        title='Legacy annotations',
        slug=slug,
        order=next_order,
        content_rich='<p>Anotações migradas do fluxo legado por página.</p>',
    )


def forwards_migrate_to_chapter_selector(apps, schema_editor):
    Annotation = apps.get_model('annotations', 'Annotation')
    BookChapter = apps.get_model('library', 'BookChapter')

    max_order_cache = {}

    def max_order_for_version(version_id):
        if version_id not in max_order_cache:
            max_order_cache[version_id] = (
                BookChapter.objects
                .filter(book_version_id=version_id)
                .aggregate(value=models.Max('order'))
                .get('value')
                or 0
            )
        return max_order_cache[version_id]

    for annotation in Annotation.objects.all().iterator():
        chapter = _resolve_chapter_for_annotation(annotation, BookChapter, max_order_for_version)
        max_order_cache[annotation.book_version_id] = max(
            max_order_for_version(annotation.book_version_id),
            chapter.order,
        )

        legacy_rects = getattr(annotation, 'rects_normalizados', None)
        if not isinstance(legacy_rects, list):
            legacy_rects = []

        legacy_selector = {}
        if getattr(annotation, 'page_number', None) is not None:
            legacy_selector['legacy_page_number'] = annotation.page_number
        if legacy_rects:
            legacy_selector['legacy_rects'] = legacy_rects

        annotation.chapter_id = chapter.id
        annotation.selector = legacy_selector
        annotation.start_offset = 0
        annotation.end_offset = 1
        annotation.excerpt = ''
        annotation.save(
            update_fields=[
                'chapter',
                'selector',
                'start_offset',
                'end_offset',
                'excerpt',
            ]
        )


def backwards_restore_legacy_fields(apps, schema_editor):
    Annotation = apps.get_model('annotations', 'Annotation')

    for annotation in Annotation.objects.all().iterator():
        selector = annotation.selector if isinstance(annotation.selector, dict) else {}
        legacy_page = selector.get('legacy_page_number')
        try:
            page_number = int(legacy_page)
        except (TypeError, ValueError):
            chapter_order = getattr(annotation.chapter, 'order', None)
            page_number = int(chapter_order) if chapter_order else 1
        page_number = max(1, page_number)

        legacy_rects = selector.get('legacy_rects')
        if not isinstance(legacy_rects, list):
            legacy_rects = []

        annotation.page_number = page_number
        annotation.rects_normalizados = legacy_rects
        annotation.save(update_fields=['page_number', 'rects_normalizados'])


class Migration(migrations.Migration):
    dependencies = [
        ('library', '0005_bookchapter_fts_index'),
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='annotations',
                to='library.bookchapter',
            ),
        ),
        migrations.AddField(
            model_name='annotation',
            name='end_offset',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='annotation',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annotation',
            name='selector',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='annotation',
            name='start_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotations_user_id_d476e1_idx',
        ),
        migrations.RunPython(
            forwards_migrate_to_chapter_selector,
            backwards_restore_legacy_fields,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='annotations',
                to='library.bookchapter',
            ),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(
                condition=models.Q(end_offset__gte=models.F('start_offset')),
                name='annotation_end_offset_gte_start_offset',
            ),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(
                fields=['user', 'book_version', 'chapter', 'start_offset'],
                name='ann_u_bv_ch_start_idx',
            ),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='rects_normalizados',
        ),
    ]
