# Generated by Django 5.2.10 on 2026-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=64)),
                ('case_number', models.CharField(max_length=128)),
                ('decision_date', models.DateField()),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('relevance', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-decision_date', '-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['court', 'decision_date'], name='caselaw_cas_court_e42446_idx'), models.Index(fields=['case_number'], name='caselaw_cas_case_nu_b04c57_idx')],
                'constraints': [models.UniqueConstraint(fields=('court', 'case_number'), name='uniq_caselaw_court_case_number')],
            },
        ),
    ]
