# Generated by Django 5.2.10 on 2026-02-24 17:46

import re
from html import unescape

from django.db import migrations, models


def _summary_to_plain_text(value: str) -> str:
    if not value:
        return ''
    text = re.sub(r'<br\s*/?>', '\n', value, flags=re.IGNORECASE)
    text = re.sub(r'</(p|h1|h2|h3|h4|h5|h6|li|blockquote)>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]+>', ' ', text)
    text = unescape(text)
    text = text.replace('\xa0', ' ')
    text = re.sub(r'\s*\n\s*', '\n', text)
    return re.sub(r'\s+', ' ', text).strip()


def forwards_copy_summary_to_ementa(apps, schema_editor):
    CaseLaw = apps.get_model('caselaw', 'CaseLaw')
    for item in CaseLaw.objects.all().iterator():
        summary = getattr(item, 'summary', '') or ''
        item.ementa_rich = summary
        item.ementa_plain = _summary_to_plain_text(summary)
        if not isinstance(item.anchors, list):
            item.anchors = []
        if not isinstance(item.tags, list):
            item.tags = []
        item.save(update_fields=['ementa_rich', 'ementa_plain', 'anchors', 'tags'])


def backwards_restore_summary(apps, schema_editor):
    CaseLaw = apps.get_model('caselaw', 'CaseLaw')
    for item in CaseLaw.objects.all().iterator():
        item.summary = getattr(item, 'ementa_rich', '') or ''
        item.relevance = 0
        item.save(update_fields=['summary', 'relevance'])


class Migration(migrations.Migration):

    dependencies = [
        ('caselaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselaw',
            name='anchors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='caselaw',
            name='ementa_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='caselaw',
            name='ementa_rich',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            forwards_copy_summary_to_ementa,
            backwards_restore_summary,
        ),
        migrations.RemoveField(
            model_name='caselaw',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='caselaw',
            name='summary',
        ),
    ]
